### ISSUE TITLE
POST data to sign_up doubt

### ISSUE THREAD

**Issue by jessicafarias** [Gokul595/api_guard#41]
Hello, I'll appreciate your help, I'm trying to use sign_up but I can't write anything but nil type.

#Front-end request
```
const signUp = async data => {
  console.log(data);
  const apiUrl = 'http://localhost:3002/users/sign_up';
  const response = await fetch(apiUrl, {
    method: 'POST',
    body: JSON.stringify(data),
  });
  return response.json();
};
```

RESPONSE: 
//What I'm sending
Object { email: "jessica2@gmail.com", name: "jessica", password: "password", password_confirmation: "password" }
loginRequest.js:2
//response
Object { status: "success", message: "Signed up successfully" }
//Dataase
#<User id: 2, name: nil, email: nil, password_digest: nil, created_at: "2021-03-14 18:56:47", updated_at: "2021-03-14 18:56:47">,

**Comment by Gokul595** [comment]
Hi @jessicafarias, can you please share your Rails development log?

**Comment by jessicafarias** [comment]
I override the controller creating an empty User with no parameters.  
It was my mistake. :cold_sweat: 

I back to the original code and change the sing_up_params to include the name in sign_up
 ```
def sign_up_params
    params.permit(:email, :password, :password_confirmation, :name)
 end
```
 
 That fixes the issue, thank you a lot anyway!.
