### ISSUE TITLE
How to issue a token outside api guard default controllers

### ISSUE THREAD

**Issue by ahmadabdelhalim** [Gokul595/api_guard#50]
I'm implementing a signup/login feature using Facebook. I want to issue a token to the client to allow the user to sign in. Is there's a way to issue a token for a different controller?

**Comment by Gokul595** [comment]
@ahmadabdelhalim Yes, you can use the `create_token_and_set_header` method directly inside any controller. This will create and set the token in response header.

```ruby
create_token_and_set_header(User.first, 'user')
```

**Comment by ahmadabdelhalim** [comment]
Great, thank you!
