### ISSUE TITLE
Rails 6.1 undefined method 'day' for 1:Integer

### ISSUE THREAD

**Issue by DonaldoSoWell** [Gokul595/api_guard#51]
**Describe the bug**
`undefined method 'day' for 1:Integer `error is raised while running one of the following commands :
- rails t
- rails c
- rails s

**Gem version (please complete the following information):**
 - Ruby: 2.7.3
 - Rails 6.1.4
 - API Guard 0.5.1

**Comment by Gokul595** [comment]
@DonaldoSoWell Sorry for checking this late. I couldn't reproduce this bug, tried with the ruby and rails version mentioned by you. Do you mind sharing the complete log that you see when you get this error?

**Comment by Gokul595** [comment]
Closing this for now. Feel free to reopen.
