### ISSUE TITLE
How to send a new access token to the browser before the old access token expire?

### ISSUE THREAD

**Issue by rkcelestial** [Gokul595/api_guard#56]
Hi,
I have an API service app with rails.
I'm getting Access-Token and Refresh-Token Once I had sign_in.
Every request I'm sending Authorization and Refresh-Token. Here I want to new access token before the current access token expire. 
In the current situation automatically I'm getting Access token expired.

How can I auto-renew a new access token?

**Comment by Gokul595** [comment]
@rkcelestial You can get new access token using this API https://github.com/Gokul595/api_guard#refresh-access-token
