### ISSUE TITLE
Add posibility to refresh expired access token

### ISSUE THREAD

**Issue by Bilanuk** [Gokul595/api_guard#65]
**Problem:**
 If access jwt token expired we can't refresh token no more. So there is no point in making refresh token with much longer lifespan.
 **My idea:**
 How about just using refresh token? I think there is no point in blacklisting them then.
 
My code example:
https://github.com/Bilanuk/api_guard/commit/b66920d06970b8bca28ad513a0b52028654cf652
![image](https://user-images.githubusercontent.com/40918746/202864999-b2ba3a15-21b9-4f3f-a43d-1d4747d9f74e.png)

**Comment by Gokul595** [comment]
@Bilanuk We can refresh expired access token using a valid refresh token (Ref: https://github.com/Gokul595/api_guard#refresh-access-token). Do you have custom routes for refreshing token, can you share your `routes.rb` file code?

**Comment by Bilanuk** [comment]
> @Bilanuk We can refresh expired access token using a valid refresh token (Ref: https://github.com/Gokul595/api_guard#refresh-access-token). Do you have custom routes for refreshing token, can you share your `routes.rb` file code?
Here is my routes:

```
Rails.application.routes.draw do 
   scope :api, defaults: {format: :json} do 
     scope :auth do 
       api_guard_routes for: "users", controller: { 
         registration:   "users/registration", 
         authentication: "users/authentication", 
         passwords:      "users/passwords", 
         tokens:         "users/tokens" 
       } 
     end 
  
     get "/user-info", to: "users#show" # just for test purpose 
   end 
 end
```

 But in tokens#create we do have before_action :authenticate_resource that triggers jwt access_token decoding. But since our token is expired we can't decode it and get 401 response.
 I did all steps for configuring refresh tokens from Readme, but still I don't understand part of expired access token.
 Or maybe I am doing something wrong?

**Comment by Gokul595** [comment]
There is a condition to skip validating the expiry when refreshing the token Ref: https://github.com/Gokul595/api_guard/blob/master/lib/api_guard/jwt_auth/authentication.rb#L44. May be the `controller_name` didn't return expected value there due to customisation. Can you please share the `users/tokens` controller code for my reference to debug?
