### ISSUE TITLE
Is this project still maintained

### ISSUE THREAD

**Issue by JamesWatling** [Gokul595/api_guard#75]
Hi, 

I have been using api_guard for many years and love it!

Starting a new project and of course reach for api_guard, but noticed it hasn't received any updates in 2 years, and seems like a risk to start a new project on a potentially unmaintained project.

Are you looking for contributors and/or actively maintaining this project?

**Comment by Gokul595** [comment]
@JamesWatling Happy to hear you love API Guard.

Yes, this is still being maintained and there are no open bugs. Planning to close the pending pull requests soon. You can safely continue using this gem. Thank you!
