### ISSUE TITLE
Unauthorized error

### ISSUE THREAD

**Issue by kcsujeet** [Gokul595/api_guard#8]
I get " unauthorized " status response, from the " authenticate_and_set_user" method. I have the Access token in my request header. 

![Screenshot from 2019-03-27 09-42-46](https://user-images.githubusercontent.com/24563569/55049596-07934b00-5075-11e9-9606-f982d22742c4.png)

The response.
 
![Screenshot from 2019-03-27 09-52-58](https://user-images.githubusercontent.com/24563569/55049869-26461180-5076-11e9-847b-3b9744290171.png)

Error log

```
Started POST "/advertisements" for 127.0.0.1 at 2019-03-27 09:42:41 +0545
Processing by AdvertisementsController#create as */*
  Parameters: {"title"=>"mobile for sale", "description"=>"as good asnew s7 for sale"}
Filter chain halted as :authenticate_and_set_user rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.2ms | ActiveRecord: 0.0ms)
```

**Comment by Gokul595** [comment]
@kcsujeet Can you please create a new token by signing in and try passing that token in the `/advertisements` request header?

If you still face the issue, please post the JWT token received in sign in response and the header value `request.headers['Authorization']` received in the `/advertisements` request.

**Comment by kcsujeet** [comment]
@Gokul595 I tried signing in and using tokens several times before posting this issue.  

Here's the lastest token i got in response header after signing in: 
` eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMCwiZXhwIjoxNTUzNzQ4OTk5LCJpYXQiOjE1NTM2NjI1OTl9.7kvNqYDgKjqwP3pwdjzal_hfdvAtkV9t2eWVL318qek `

I tried using this token to make a post request at  ` /advertisements ` .

Here's the Authorization request header. 
```
 Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMCwiZXhwIjoxNTUzNzQ4OTk5LCJpYXQiOjE1NTM2NjI1OTl9.7kvNqYDgKjqwP3pwdjzal_hfdvAtkV9t2eWVL318qek 
```
I used insomnia to make the request. here's the screenshot of the header.
![Screenshot from 2019-03-27 10-45-51](https://user-images.githubusercontent.com/24563569/55051513-8ab89f00-507d-11e9-80e4-6a80a4eac547.png)

**Comment by Gokul595** [comment]
@kcsujeet Is this related to issue #8? Can you please check and confirm?

**Comment by kcsujeet** [comment]
@Gokul595 I'm afraid not. Issue [#7](https://github.com/Gokul595/api_guard/issues/7) was solved thanks to you. But this issue still persists. 

Also, when I refresh tokens, I get new "access and refresh" tokens in response header. But the old access token still works. only the old refresh token is invalidated. why isn't the token blacklisting working? Am i missing something?

**Comment by Gokul595** [comment]
@kcsujeet As the refresh token call is working successfully, I am wondering how it doesn't work for this API as we authenticate on refresh token call also. 

Can you please help me with below info?
1. **api_guard.rb** initializer file
2. `token_issued_at` value of the user if you enabled [Invalidating token on password change](https://github.com/Gokul595/api_guard#invalidate-tokens-on-password-change)

**Comment by Gokul595** [comment]
@kcsujeet As the refresh token call is working successfully, I am wondering how it doesn't work for this API as we authenticate on refresh token call also. 

Can you please help me with below info?
1. **api_guard.rb** initializer file
2. `token_issued_at` value of the user if you enabled [Invalidating token on password change](https://github.com/Gokul595/api_guard#invalidate-tokens-on-password-change)

And, regarding the token blacklisting on refreshing the access token - This is not included in this gem. Token will be blacklisted only on the successful logout. If you feel token needs to be blacklisted on refreshing I am happy to add a configuration to enable blacklisting on token refreshing.

**Comment by kcsujeet** [comment]
@Gokul595 here's the initializer file. 
```
ApiGuard.setup do |config|
  # Validity of the JWT access token
  # Default: 1 day
  config.token_validity = 1.day

  # Secret key for signing (encoding & decoding) the JWT access token
  # Default: 'secret_key_base' from Rails secrets
  config.token_signing_secret = 'my_signing_secret'

  # Invalidate old tokens on changing the password
  # Default: false
  config.invalidate_old_tokens_on_password_change = false
end

```
As you can see i've not enabled invalidating the token. 

Regarding the token blacklisting, i think this feature should be there. since I get a new acccess token upon refreshing my token, i don't see any point in the old token being still valid.

**Comment by Gokul595** [comment]
@kcsujeet I will add the option to blacklist token on token refreshing.

Regarding the issue you're facing, can you add below code in your `AdvertisementsController#create` action and post the output so that, we can confirm whether the token is properly being decoded or not.

```ruby
@token = 'eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NTM4Nzg2MTEsImlhdCI6MTU1Mzc5MjIxMX0.dv49Y5jExQdGx80XGEJFOtF8GDC4pNwqLaxNDdT4S4k'

p decode_token, @decoded_token[:"user_id"]
```

Set value of `@token` to the access token you got in the sign in response.

**Comment by Gokul595** [comment]
@kcsujeet Closing this as this is inactive for 1 week. Feel free to reopen.

**Comment by Gokul595** [comment]
@kcsujeet FYI, Added option to blacklist token on refresh. Ref: #9
